name: Run Smoke Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  TAG: "@smoke"        # default tag filter
  THREAD_COUNT: "2"    # default parallel threads
  BROWSER: "chromium"  # default browser

jobs:
  playwright-smoke-tests:
    name: Run Smoke Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      #Install Maven 3.9.9
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.7.0
        with:
         checkout-fetch-depth: 0
         java-version: 17
         java-distribution: temurin
         maven-version: 3.9.9

      #Verify Maven installation
      - name: Verify Maven version
        run: mvn --version

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Maven dependencies (skip tests)
        run: mvn install -DskipTests

      - name: Install Playwright browsers
        run: mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install"

      - name: Run tests
        run: |
#          echo "Running tests with TAG=${TAG}, THREAD_COUNT=${THREAD_COUNT}, BROWSER=${BROWSER}"
          mvn clean compile test \
            -Dcucumber.filter.tags="(${TAG} and (not @ignore))" \
            -Ddataproviderthreadcount=${THREAD_COUNT} \
            -DBROWSER=${BROWSER}
